*** Variables ***
# login
${Emaillogin}                      sysadmin@qacoders.com 
${Passwordlogin}                   1234@Test 
# Departamento
${Nomedepartamento12}              Departamento12
${Caracteres@}                     Caracteres@ 
${Departamento51}                  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#Diretoria
${Numeros50}                       Números50
${Diretoria@}                      Diretoria@